### ISSUE TITLE
Tab key not working to get menu

### ISSUE THREAD

**Issue by jowasp** [Ali-Razmjoo/OWASP-ZSC#14]
I'm trying to generate a shell code. I'm using OSX. When I try to use the tab key as explained on the user guides it does not work I get "command not found"
![screenshot 2016-02-05 14 50 36](https://cloud.githubusercontent.com/assets/6704344/12855798/d8220922-cc17-11e5-9a74-cf0695944ace.png)

**Comment by Ali-Razmjoo** [comment]
Hello,

Are you using the last version ? What's your python version ? We had same problem with python 3.x which is fixed.

Please share details about your os and python version.

Thank you.

**Comment by Ali-Razmjoo** [comment]
It's seems problem fixed by include the last version in the software, you can install last version or download last version of project, it's imported in project.

![attach](https://cloud.githubusercontent.com/assets/7676267/12863376/b917a24a-cc89-11e5-8cd2-1501c77b6260.png)

Please test it, if you have any problem or not, Please share the result.

Thank you

**Comment by jowasp** [comment]
Now the tab key function works
![screenshot 2016-02-06 10 28 11](https://cloud.githubusercontent.com/assets/6704344/12867157/70981a94-ccbc-11e5-98df-797b017806d8.png)
